updating my fork (#2)
* Move nginx-proxy

* Added TrendMicro to Security Section

* Reverted erroneous change to Links section.

* changed owner

* Update dependency sitemap to v6

* fix sitemap build step

* Added Dist to Registry list

* Update dependency eslint-config-airbnb-base to v14.1.0

* Use github actions

* Add codeowners

* Pin dependency minimist to 1.2.5

* Update travis

* Update travis

* Whitelist awesome

* Whitelist awesome

* Add badges

* Update dependency sitemap to v6.1.0

* Update dependency fs-extra to v9

* Update dependency prettier to v2

* Update dependency prettier to v2.0.1

* Update dependency eslint-config-prettier to v6.10.1

* Add "An Annotated Docker Config for Frontend Web Development"

Article detailing a complete production-ready Docker config for local frontend web development.

* Update dependency prettier to v2.0.2

* Add "Oh My Zsh Installer for Docker" (#839)

* Add "Oh My Zsh Installer for Docker"

* Update dependency eslint-plugin-import to v2.20.2

* add Dockerfile Linter action

* add url to action and sort

* Update dependency prettier to v2.0.3

* Update dependency prettier to v2.0.4

* Adding Dockershelf to the list

A repository that serves as a collector for docker recipes that are universal, efficient and slim.

* Correcting typo.

* Fix #845

* Add reminder

* PR for #844

* Hotfix order

* Github Actions for PR

* Try travis

* Improve error logging

* Fix regex for links

* Improve error logging

* Fix exclude website list

* Refactor exclude list

* Refactor exclude list

* Remove unused dependecies

* Delete renovate.json

* Fix github action path

* Setup github token

* Display env var nicely

* Dont skip cache, apparently

* Update reference to test script

* Add full path

* Replace showdown options

* Add category runtime

* Add Android in Containers

* Add Deepfence in Security section

* Add 'edited by deepfence' for the changes

* Ouroboros no longer maintained.

Added Skull.

* Change position of :skull: for link to repository Ouroboros

* Fix redirect to www for link https://packer.io/

* Use correct reference for mention of deepfence

* Add Pull Dog

* Update README.md

Co-Authored-By: Sandro <sandro.jaeckel@gmail.com>

* Add willfarrell/docker-autoheal to Monitoring

* Exclude github apps

* Update README.md

* Fix packer.io redirect

* Fix packer.io redirect

* Update README.md

add ansible-bender.

* add cekit in builder section.

* Remove duplicate

* Added DockerStacks app link and descriptions

* Sorted the list A-Z

* Added site link, removed github repo link

* Update README.md

add 3 YouTube playlist courses.

* Update README.md

sort abc + add time

* exclude cycle io in tests

* Delete FUNDING.yml

* add "docker pushrm", a Docker CLI plugin that that lets you push the README.md file from the current directory to Docker Hub, Quay, Harbor.

* Fix vagrantup link

fixes failing test in https://github.com/veggiemonk/awesome-docker/pull/863

* fix badge

* Update README.md

* Update README.md

* fix redirect urls

Twistlock acquired...

* Added trivy

* add Docker garbage collector - docker_gc

* add Docker garbage collector - docker_gc

* Bump lodash from 4.17.15 to 4.17.19

Bumps [lodash](https://github.com/lodash/lodash) from 4.17.15 to 4.17.19.
- [Release notes](https://github.com/lodash/lodash/releases)
- [Commits](https://github.com/lodash/lodash/compare/4.17.15...4.17.19)

Signed-off-by: dependabot[bot] <support@github.com>

* remove docker_lint from project atomic

the repository was deleted

* Updating werf description and moving to Deployment

* Docker Quick Tutorial - Introduces you to the official Getting Started tutorial using Windows 10 and Hyper-V.

* Update README.md

Fix alphabetical order on contribution.

* Update README.md

Docker Quick Tutorial

* Add Gebug

Gebug - A tool that makes debugging of Dockerized Go applications super easy by enabling Debugger and Hot-Reload features, seamlessly.

* Update README.md

* Bump elliptic from 6.5.2 to 6.5.3

Bumps [elliptic](https://github.com/indutny/elliptic) from 6.5.2 to 6.5.3.
- [Release notes](https://github.com/indutny/elliptic/releases)
- [Commits](https://github.com/indutny/elliptic/compare/v6.5.2...v6.5.3)

Signed-off-by: dependabot[bot] <support@github.com>

* update redirect links: docker => mirantis

* Fix Portus catagory

* Added 'The Docker Handbook' in the 'Where to start' section

* Updated the description with a better one

* Added Docker.Registry.DotNet to API Client section

Thanks!

* Fix link for mesosphere dc/os platform

* Fixes requested by @agebhar1

Link is fixed.

* Bump node-fetch from 2.6.0 to 2.6.1

Bumps [node-fetch](https://github.com/bitinn/node-fetch) from 2.6.0 to 2.6.1.
- [Release notes](https://github.com/bitinn/node-fetch/releases)
- [Changelog](https://github.com/node-fetch/node-fetch/blob/master/docs/CHANGELOG.md)
- [Commits](https://github.com/bitinn/node-fetch/compare/v2.6.0...v2.6.1)

Signed-off-by: dependabot[bot] <support@github.com>

* Fix owner link for "rocker-compose"

* Moving grammarly link to the end of the readme

* Add Storidge

* Add sue

* security updates

* Update node version

* fix links

* Added a git tutorial in videos sections

* Added VS Code & Docker course

* Changed order of the video link

* Change order of docker video entries, add creator

* added missing discription & $$

* Add ckron

* Update README.md

Add reference to creator of ckron repository

* Fix link syntax to contributor

* Fix link to hanselman asp.net core article

* Remove anchor tag reference from Storidge link

* Fix link to "contributor code of conduct"

* Typos

* Added Yacht to web Section

Yacht is a web interface for managing docker containers with an emphasis on templating to make deployments as easy as possible. Think of it like a decentralized app store for servers that anyone can make packages for.

* Update README.md

* Typo: mulitiple -> multiple

* Change links to redirected urls

* A cli-plugin for docker to automatically manage image digests by tracking them in a separate Lockfile.

* Fix link for trivy

* Typo

* Added resource for top docker courses & tutorials.

* Keep only external links checks

* Move tests into subdir, QA

* Add script for running all tests locally, extract duplicate methods into helper

* "analzying" -> "analyzing"

* Rename files

* Update README.md

* Update README.md

* Remove "that that"

* use latest version for GitHub Action(s)

> Run actions/setup-node@83c9f7a7df54d6b57455f7c57ac414f2ae5fb8de
> Error: Unable to process command '::add-path::/opt/hostedtoolcache/node/12.19.0/x64/bin' successfully.
> Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

* fix redirect of »Sysdig Secure« link

* Update README.md

* README.md: IDE integrations

* update text regarding container-registry.com make clear its harbor based and has a free tier with private repos

* Split Terminal section to subsections

To make it easier to find a good TUI dashboard (ctop, lazydocker) it's better to group them together

* Update README.md

Co-authored-by: Julien Bisconti <veggiemonk@users.noreply.github.com>

* Update README.md

Co-authored-by: Julien Bisconti <veggiemonk@users.noreply.github.com>

* TOC terminal sections

* Add dockerfile best practices

* Change weekly archives to newsletter link

Link redirected to newsletter page, so why bot use newsletter directly as ressource

* Add cli template engine "dcinja" tutorial in README

* Add bunkerized-nginx to Reverse Proxy section

More info about bunkerized-nginx at https://github.com/bunkerity/bunkerized-nginx.

* Added the updated link to The Docker Handbook

* Add Krane

* Order alphabetically

* Add mannng.com to excluded links in tests

manning.com runs on cloudflare and has curl protection enabled (error code: 1020% when trying to curl)

* Fix links for Gitlab Container Registry, Vagrant and CodeShip

* Add mannng.com to excluded links in tests

manning.com runs on cloudflare and has curl protection enabled (error code: 1020% when trying to curl)

* Fix links for Gitlab Container Registry, Vagrant and CodeShip

* Change gitlab registry link from ee back to ce

* Add Docker + cloud-init Terraform module to list

* Add dockerfilegraph (https://github.com/patrickhoefler/dockerfilegraph) by @PatrickHoefler

* Update Dlayer (layer analyser)

* Added appfleet, a new edge compute platform

* Mark clj-docker-client as complete, update URL

* Update README.md

Hi, Added a resource page that will be appreciated by your audience

* Bump elliptic from 6.5.3 to 6.5.4

Bumps [elliptic](https://github.com/indutny/elliptic) from 6.5.3 to 6.5.4.
- [Release notes](https://github.com/indutny/elliptic/releases)
- [Commits](https://github.com/indutny/elliptic/compare/v6.5.3...v6.5.4)

Signed-off-by: dependabot[bot] <support@github.com>

* Sorting entries

* Fix arm entries

Co-authored-by: Julien Bisconti <veggiemonk@users.noreply.github.com>
Co-authored-by: Julien Bisconti <julien.bisconti@gmail.com>
Co-authored-by: robmaynardjr <robmaynardjr@gmail.com>
Co-authored-by: Manuel Schmid <mash1t@users.noreply.github.com>
Co-authored-by: Renovate Bot <bot@renovateapp.com>
Co-authored-by: Stephen Haynes <sh@synk.net>
Co-authored-by: Andrew Welch <khalwat@users.noreply.github.com>
Co-authored-by: Andreas Gebhardt <agebhar1@googlemail.com>
Co-authored-by: Deluan Quintão <github@deluan.com>
Co-authored-by: czulak <lukasz.czulak@gmail.com>
Co-authored-by: Luis Alejandro Martínez Faneyth <luis@luisalejandro.org>
Co-authored-by: Bruno <brunocascio@gmail.com>
Co-authored-by: Ramanan R <ramanan-r@users.noreply.github.com>
Co-authored-by: PatSki123 <patricksikorski@gmail.com>
Co-authored-by: Mathias Lykkegaard Lorenzen <mathias.lorenzen@live.com>
Co-authored-by: Sandro <sandro.jaeckel@gmail.com>
Co-authored-by: Patryk Ptasiński <github@ipepe.pl>
Co-authored-by: Thomas Ruf <grerrg@users.noreply.github.com>
Co-authored-by: Subhadip Naskar <softwarefreak89@gmail.com>
Co-authored-by: Paris Nakita Kejser <parisnakitakejser@users.noreply.github.com>
Co-authored-by: Christian Korneck <christian@korneck.de>
Co-authored-by: Frani <frani@users.noreply.github.com>
Co-authored-by: Catalin Jora <catalin.jora@gmail.com>
Co-authored-by: Dmitry Malinin <dmitry@malinin.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Dmitry Shurupov <dmitry.shurupov@flant.com>
Co-authored-by: returnvalue <chris.fiandaca@outlook.com>
Co-authored-by: moshebe <moshebe123@gmail.com>
Co-authored-by: Tony Huang <tony24681379@users.noreply.github.com>
Co-authored-by: Farhan Hasin Chowdhury <mail@farhan.info>
Co-authored-by: Jaben Cargman <Jaben@users.noreply.github.com>
Co-authored-by: Peter Thaleikis <spekulatius@users.noreply.github.com>
Co-authored-by: Alexander Klus <Alexander_@hotmail.nl>
Co-authored-by: theAkito <the@akito.ooo>
Co-authored-by: Anurag Choudhary <anurag.choudhary2@gmail.com>
Co-authored-by: Brian Christner <brian.christner@gmail.com>
Co-authored-by: Nicolas Martinez <17040442+nicomt@users.noreply.github.com>
Co-authored-by: Manuel Schmid <manuel.schmid@odt.net>
Co-authored-by: SelfhostedPro <66331933+SelfhostedPro@users.noreply.github.com>
Co-authored-by: Michael Perel <michaelsethperel@gmail.com>
Co-authored-by: tushar926 <74056573+tushar926@users.noreply.github.com>
Co-authored-by: Ashley Davis <ashley@codecapers.com.au>
Co-authored-by: Sergey Ponomarev <stokito@gmail.com>
Co-authored-by: Vadim Bauer <vb@8gears.com>
Co-authored-by: Falldog <falldog@hardcoretech.co>
Co-authored-by: Bunkerity <54334437+bunkerity@users.noreply.github.com>
Co-authored-by: David Castaneda <dcast188@fiu.edu>
Co-authored-by: Chris Tippett <git@christippett.dev>
Co-authored-by: Patrick Hoefler <patrick.hoefler@gmail.com>
Co-authored-by: Dmitriy <dakulovgr@gmail.com>
Co-authored-by: Rahul De <rahul080327@gmail.com>
Co-authored-by: sherihans123 <75074073+sherihans123@users.noreply.github.com>